import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { createDebt, deleteDebt, getDebtSummary, getDebts, settleDebt, type Debt, type DebtSummary } from '../services/api'

export default function Debts(){
 const [items,setItems]=useState<Debt[]>([]); const [summary,setSummary]=useState<DebtSummary>({lent:0,borrowed:0,net:0}); const [person,setPerson]=useState(''); const [amount,setAmount]=useState(''); const [type,setType]=useState<'lent'|'borrowed'>('lent'); const [description,setDescription]=useState(''); const [dueDate,setDueDate]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function load(){try{const [d,s]=await Promise.all([getDebts(),getDebtSummary()]);setItems(d);setSummary(s)}catch(e){setError(e instanceof Error?e.message:'Failed to load records')}} useEffect(()=>{load()},[])
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{await createDebt({person,amount,type,description,dueDate:dueDate||undefined});setPerson('');setAmount('');setDescription('');setDueDate('');await load()}catch(e){setError(e instanceof Error?e.message:'Failed to save')}finally{setBusy(false)}}
 async function settle(id:string){try{await settleDebt(id);await load()}catch(e){setError(e instanceof Error?e.message:'Failed to settle') }}
 async function remove(id:string){if(!confirm('Delete this record?'))return;try{await deleteDebt(id);await load()}catch(e){setError(e instanceof Error?e.message:'Failed to delete')}}
 return <div className="page"><div className="page-header"><div><h2>Money Owed</h2><p>Track money you have lent and money you owe to others.</p></div></div><div className="debt-summary"><div className="summary-box"><span>People owe you</span><strong>₹{summary.lent.toLocaleString('en-IN')}</strong></div><div className="summary-box"><span>You owe</span><strong>₹{summary.borrowed.toLocaleString('en-IN')}</strong></div><div className="summary-box"><span>Net receivable</span><strong className={summary.net>=0?'positive':'negative'}>₹{summary.net.toLocaleString('en-IN')}</strong></div></div><div className="debt-layout"><form className="section-card debt-form" onSubmit={submit}><div className="card-header"><div><h3>Add a record</h3><p>Record a loan, advance or amount owed.</p></div></div><label>Person<input value={person} onChange={e=>setPerson(e.target.value)} required placeholder="Person's name"/></label><label>Amount (₹)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required placeholder="0.00"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value as 'lent'|'borrowed')}><option value="lent">They owe me</option><option value="borrowed">I owe them</option></select></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional note"/></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Saving...':'Add record'}</button></form><div className="section-card"><div className="card-header"><div><h3>Records</h3><p>{items.filter(x=>x.status==='pending').length} pending record(s)</p></div></div><div className="debt-list">{items.length===0?<div className="empty-state">No money-owed records yet.</div>:items.map(x=><div className={`debt-item ${x.status}`} key={x._id}><div className="debt-main"><div className="debt-person">{x.person}<span className={`debt-badge ${x.type}`}>{x.type==='lent'?'OWES YOU':'YOU OWE'}</span>{x.status==='settled'&&<span className="debt-badge settled">SETTLED</span>}</div><div className="debt-meta">{x.description||'No description'}{x.dueDate?` · Due ${new Date(x.dueDate).toLocaleDateString()}`:''}</div></div><strong className={x.type==='lent'?'positive':'negative'}>₹{x.amount.toLocaleString('en-IN')}</strong><div className="debt-actions">{x.status==='pending'&&<button onClick={()=>settle(x._id)}>Settle</button>}<button onClick={()=>remove(x._id)}>Delete</button></div></div>)}</div></div></div></div>
}
